'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import AboutSection from '@/components/AboutSection';
import ServicesSection from '@/components/ServicesSection';
import CarSection from '@/components/ProcessSection';
import TestimonialsSection from '@/components/TestimonialsSection';
import FAQSection from '@/components/FAQSection';
import ContactSection from '@/components/ContactSection';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <div
      className="flex min-h-screen flex-col"
      style={{
        background: 'linear-gradient(120deg, #3b82f6 0%, #ffffff 100%)',
        minHeight: '100vh',
        backgroundAttachment: 'fixed',
      }}
    >
      <main className="flex-1 mx-auto">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <AboutSection />
        <ServicesSection />
        <CarSection />
        <TestimonialsSection />
        <FAQSection />
        <ContactSection />
        <Footer />
      </main>
      
    </div>
  );
}