'use client';

import React from 'react';
import HeroSection from '@/components/HeroSection';
import AboutSection from '@/components/AboutSection';
import ServicesSection from '@/components/ServicesSection';
import CarSection from '@/components/ProcessSection';
import TestimonialsSection from '@/components/TestimonialsSection';
import FAQSection from '@/components/FAQSection';
import ContactSection from '@/components/ContactSection';
import CTASection from '@/components/CTASection';
import Footer from '@/components/Footer';

export default function HomePage() {
  return (
    <div className="flex min-h-screen flex-col">
      <main className="flex-1 container mx-auto ">
        {/* Components generated by the builder will be added here */}
      
        <HeroSection />
        <AboutSection />
        <ServicesSection />
        <CarSection />
        <TestimonialsSection />
        <FAQSection />
        <ContactSection />
        <CTASection />
        <Footer />
      </main>
      
    </div>
  );
}